### ISSUE TITLE
Error using Python3 - python3 manage.py db upgrade - except ImportError, e:

### ISSUE THREAD

**Issue by royopa** [hustlzp/Flask-Boost#18]
(venv)rodrigo@rodrigo-xubuntu:~/projects/flask_boost_site$ python3 manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from application import create_app
  File "/home/rodrigo/projects/flask_boost_site/application/__init__.py", line 19, in <module>
    from config import load_config
  File "/home/rodrigo/projects/flask_boost_site/config/__init__.py", line 18
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
(venv)rodrigo@rodrigo-xubuntu:~/projects/flask_boost_site$

**Comment by hustlzp** [comment]
I have fix some Python3 issues with 2 commits：

* 2f29a6f0a87b201ac0b983094826b06145c333e1
* 59854731162c25c75304798b62f6541bb9646eee

After that I found the `Flask-Uploads` package does't support Python3...

I think I will report this issue to `Flask-Uploads`.

Or I may take some time to find a package to replace it.

**Comment by hustlzp** [comment]
Seems that somebody has already report this:

https://bitbucket.org/leafstorm/flask-uploads/issue/14/iteritems-in-configure_uploads

**Comment by royopa** [comment]
Thanks @hustlzp. I voted for the issue in flask-uploads.

**Comment by hustlzp** [comment]
At last I remove `Flask-Uploads` in order to support Python 3.x.
