### ISSUE TITLE
请教fis之后资源文件被打上md5标签

### ISSUE THREAD

**Issue by daimon99** [hustlzp/Flask-Boost#23]
请教fis之后资源文件被打上md5标签
但是pages里面的template文件引用的资源名称没变
这个怎么处理？

**Comment by hustlzp** [comment]
好的，我晚上来看看。

**Comment by daimon99** [comment]
哦，我找到原因了。我得把templates的文件目录切换到output/pages下。。。不能用原来的applicatoin/pages

**Comment by hustlzp** [comment]
对的。

会根据环境（生产、开发）自动切换templates文件目录：

https://github.com/hustlzp/Flask-Boost/blob/master/flask_boost/project/application/__init__.py#L87-L102
