### ISSUE TITLE
Add info about how to deploy on apache

### ISSUE THREAD

**Issue by ZeroCool940711** [hustlzp/Flask-Boost#25]
Hi bro, do you think you could info about how to deploy a web app made using flask-boost on apache?

**Comment by hustlzp** [comment]
This [post](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension) may help you.

**Comment by ZeroCool940711** [comment]
Thanks, I will try using mod_proxy but what about using mod_wsgi?
Could be possible to use it to deploy flask-boost web apps?

**Comment by hustlzp** [comment]
Or you can try mod_wsgi to deploy Flask app. (So Gunicorn is not needed.)

See this [post](http://werkzeug.pocoo.org/docs/0.11/deployment/mod_wsgi/)。

**Comment by hustlzp** [comment]
And this [post](http://flask.pocoo.org/docs/0.10/deploying/mod_wsgi/).

The file [wsgi.app](https://github.com/hustlzp/Flask-Boost/blob/master/flask_boost/project/wsgi.py) in Flask-Boost may rename to `yourapplication.wsgi` with content:

```py
from application import create_app

application = create_app()
```

so it can be recognized by `mod_wsgi`, have a try bro, my English is not pretty good but I hope you can understand what I'm saying.

**Comment by ZeroCool940711** [comment]
Thanks for the help bro I will try right now and tell you if it work so if anyone else want to do the same they can use this issue as a reference, and don't worry your English is even better than mine.

**Comment by ZeroCool940711** [comment]
I can not make it work, it sends me to a blank page when I visit the url for the web Im trying to configure.

**Comment by hustlzp** [comment]
OK, I will try in my spare time, thanks.

**Comment by ZeroCool940711** [comment]
Ok, if you find a way to make it work let me know, I will keep trying to see if I can find something that can help with it.

**Comment by hustlzp** [comment]
Hi, sorry for replying too late.

I try to setup Apache2 as a reverse proxy according to [this post](https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension), and it works.

**Comment by hustlzp** [comment]
```sh
$ a2enmod
$ proxy proxy_ajp proxy_http rewrite deflate headers proxy_balancer proxy_connect proxy_html
```

then copy-and-paste the below block of configuration to `/etc/apache2/sites-available/default`:

```
<VirtualHost *:80>
    ProxyPreserveHost On

    # Flask app runs at port 8080
    ProxyPass / http://0.0.0.0:8080/
    ProxyPassReverse / http://0.0.0.0:8080/

    ServerName http://www.yourdomain.com
</VirtualHost>
```

then run:

```sh
$ service apache2 restart
```
