### ISSUE TITLE
SQLAlchemy table autoloading

### ISSUE THREAD

**Issue by jfduque** [hustlzp/Flask-Boost#26]
Hi Zhipeng, thanks for this awesome package.

I'm used to design my own database tables, relationships and primary keys, and then use SQLAlchemy autoloading function to create table models. The database is shared among other applications, so I like to do migrations manually, without using Flask-Migration and Alembic.

This is a example model (before using Flask-Boost), `accounts.py`

`from app import app, db`
`main_engine = db.get_engine(app, bind=None)`

`class Accounts(db.Model):`
`    __tablename__ = 'accounts'`
`    __table_args__ = {'autoload':True, 'autoload_with':main_engine}`

Now that I'm using Flask-Boost, first I type `boost new model accounts` to generate the model, and then use tools like [sqlacodegen](https://pypi.python.org/pypi/sqlacodegen) to complete the model's definition. Each time I update my database schema, I need to regenerate my models. 

Is there a way to use SQLAlchemy autoloading feature with Flask-Boost?

Thanks in advance.

**Comment by hustlzp** [comment]
You can use sqlacodegen to generate model codes to a single python file:

```sh
sqlacodegen mysql://root:@localhost/database --outfile ./application/models/models.py
```

[application/models/_base.py](https://github.com/hustlzp/Flask-Boost/blob/master/flask_boost/project/application/models/_base.py) remains the same, and [application/models/\_\_init\_\_.py](https://github.com/hustlzp/Flask-Boost/blob/master/flask_boost/project/application/models/__init__.py) can be:

```py
from ._base import db
from .models import *
```

If so, there is no need to use `boost new model accounts` command.

Then you can make a query in controller (such as [application/controllers/account.py](https://github.com/hustlzp/Flask-Boost/blob/master/flask_boost/project/application/controllers/account.py)) as follows:

```py
from ..models import db, User

db.session.query(User).filter(User.id == 1)
```

Hope that'll be helpful to you.

**Comment by jfduque** [comment]
Hi, thanks for the quick response.

This is exactly what i'm doing right now, and it works fine. But, as I said, it requires manual model generation, and that's what i'm trying to avoid, since my database is shared with other applications (database schema changes must be seen and learned by the application and not the other way).

It's just a matter of preference, i've noticed that startup time is much faster this way.

I've tried to setup SQLAlchemy to do a [lazy setup](http://flask.pocoo.org/snippets/22/), but i honestly do not know how.

Thank you for your help.

**Comment by hustlzp** [comment]
Oh I understand what you mean now. You just wanna to create model classes on the fly without generate model files manually?

I think you can try:

(1) Execute sqlacodegen everytime when init the Flask app, so if the database changes, you just need to restart the app.

```py
def create_app():
    ...
    exec('sqlacodegen mysql://root:@localhost/database --outfile ./application/models/models.py')
    ...
```

(2) You can exec the output codes of sqlacodegen

http://stackoverflow.com/a/701810/1954737
