### ISSUE TITLE
Question：How to generate table with SQLAlchemy?

### ISSUE THREAD

**Issue by yileye** [hustlzp/Flask-Boost#30]
I noticed the database object file in ‘/home/yileye/project/monitor/application/models‘

And after I run the command ’boost new model‘ ，I can see the new model file in this path

But how I use this file to generate the table in mysql?

**Comment by hustlzp** [comment]
Copy from README:

Create database with name your_project_name and encoding utf8.

Update SQLALCHEMY_DATABASE_URI in config/development.py as needed.

Then init tables:

```
python manage.py db upgrade
```

**Comment by yileye** [comment]
ok.thank you
